### ISSUE TITLE
bootstrap tooltips stoped working

### ISSUE THREAD

**Issue by renathy** [brianchance/knockout-x-editable#26]
When I try to add tooltip to text (data-toggle="tooltip" data-placement="left" title="Tooltip on left"), editor doesn't work (it doesn't open).

If I try this without knockout extension in jsfiddler, it works.
If I try to add this here http://jsfiddle.net/jjrohrer/qh3bZ/, it stop working.

The same happens inside my application.

**Comment by brianchance** [comment]
looks like x-editable uses the toggle attribute to indicate what opens the editor click|dblclick|mouseenter|manual (default click). Since it is set and not one of those values, nothing triggers the editor. I tried data-toggle='mouseenter' and it works.

Basically, both are using the same attribute and getting in each others way.

**Comment by renathy** [comment]
I have tried 'mouseenter' and it works.  However, I didn't actually get, why 'tooltip' doesn't work and if it shold be considered as x-editable bug (related to integration with bootstrap) or not?

**Comment by brianchance** [comment]
It is because both bootstrap and x-editable are using the same toggle
attribute for different purposes. I would see if x-editable has a
workaround.
